language: objective-c
before_install:
- cd Example && pod install && cd $TRAVIS_BUILD_DIR
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/HPKDateFormatter.xcworkspace -scheme HPKDateFormatter-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
